name: WhatsApp Bot CI

on:
  push:
    paths:
      - "whatsapp/**"
  pull_request:
    paths:
      - "whatsapp/**"

jobs:
  whatsapp-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: cd whatsapp && npm install

      - name: Build Check
        run: cd whatsapp && npm run build
